language: node_js
node_js:
  - "4"
  
script: 
  - karma start --browsers Firefox --single-run
  - mocha server/test

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
