angular.module('ProjectHands')

    .provider('Languages', function () {

        this.HE = {
            TEAM: 'צוותים',
            USERS: 'משתמשים',
            SELECTED_TEAM_NAME: 'חברי צוות',
            SCHEDULE: 'לוח שנה',
            USER_DETAILS: 'פרטי משתמש',
            NAME: 'שם:',
            EMAIL: 'דוא"ל:',
            PHONE: 'מס טלפון:',
            REGISTER_DATE: 'תאריך הצטרפות:',
            APPROVE_USER: 'אשר משתמש',
            DELETE_USER: 'מחק משתמש',
            JOIN_REQUESTS: 'בקשות הצטרפות',
            TASKS: 'משימות',
            TOOL_BOX: 'ארגז הכלים',
            MY_TEAM: 'הצוות שלי',
            PLANNED_RENOVATIONS: ' שיפוצים מתוכננים',
            USER_PROFILE: 'פרופיל משתמש',
            CHAT: 'צ"אט',
            DELETE: 'מחיקה',
            ADD_TEAM_MEMBERS: 'הוספת חברי צוות',
            JOIN_DATE: 'תאריך הצטרפות:',
            USER_ID: 'תעודת זהות:',
            ADDRESS: 'כתובת:',
            ABOUT_ME: 'קצת עליי:',
            LOGIN_PAGE: 'דף כניסה',
            RENOVATION_NUMBER_I_AM_IN: 'מס שיפוצים בהם השתתפתי:',
            REQUIRED: 'שדה חובה',
            WRONG_EMAIL: ' אימייל שגוי',
            PASSWORD: 'סיסמה',
            FORGOT_PASSWORD: 'שכחתי סיסמה',
            PASSWORD_LENGTH: 'דרושים לפחות 9 ספרות',
            PASSWORD_MIN_LENGTH: 'דרושים לפחות 8 תווים',
            PASSWORD_TIP: ' דרושה סיסמה באנגלית עם אות גדולה, אות קטנה ומספר',
            LOGIN: 'כניסה',
            COMPLETE_REGISTERATION: 'השלם תהליך הרשמה',
            ILLEGAL_NUMBER: 'מספר אינו חוקי',
            VOLUNTEERING_AREA: 'אזור בו אתה יכול להתנדב - ',
            MULTIPLE_AREAS_CAN_BE_SELECTED: 'ניתן לבחור כמה אזורים',
            PREFERED_DAY: 'אם יש לך יום קבוע בשבוע שהיית מעדיף - אנא ציין:',
            TIME_IN_DAY: 'בוקר - 9:00 עד 14:00 אחה"צ - 16:00 עד 21:00',
            DO_YOU_WANT_TO_BE_TEAM_LEAD: 'האם את/ה רוצה להיות ראש צוות?',
            TEAM_LEAD_ROLE: 'לראש הצוות יש שני תפקידים עיקריים: לבקר בבית המיועד לשיפוץ ולהכיןתוכנית, ולהיות אחראי על התיאומים מול הצוות שלו.',
            PREFERED_HATED_FIELD: ' *** האם יש תחום טכני ספציפי שאתה טוב/מנוסה בו?',
            PREFERED_HATED_FIELD_EXAMPLE: 'לדוגמא: בנייה בעץ, קרמיקה, חשמל, מנעולים, תריסים, צבע, עיצוב פנים וכו” כל מה שיכול לעזור...',
            REGISTER_MESSAGE: 'להתנדבות בפרויקט ידיים',
            REGISTERED_SUCCESSFULLY: 'ההרשמה בוצעה בהצלחה',
            CHECK_EMAIL_TO_CONTINUE: 'בדוק את האימייל שלך בכדי להמשיך בתהליך',
            FULL_NAME: 'שם פרטי ושם משפחה',
            BACK_TO_HOME_PAGE: 'חזרה לדף הבית',
            BUTTON_LANG_HE: 'עברית',
            BUTTON_LANG_AR: 'ערבית'
        };

        this.AR = {
            TEAM: 'الفرق',
            USERS: 'المستخدمين',
            SELECTED_TEAM_NAME: 'اعضاء الفريق',
            SCHEDULE: 'التقويم',
            USER_DETAILS: 'معلومات المستخدم',
            NAME: 'الأسم:',
            EMAIL: 'البريد الألكتروني:',
            PHONE: 'رقم التلفون:',
            REGISTER_DATE: 'تاريخ التسجيل:',
            APPROVE_USER: 'تأكيد المستخدم',
            DELETE_USER: 'مسح المستخدم',
            JOIN_REQUESTS: 'طلبات الانضمام',
            TASKS: 'المهام',
            TOOL_BOX: 'الأدوات',
            MY_TEAM: 'طاقمي',
            PLANNED_RENOVATIONS: ' التصليحات المخطط لها',
            USER_PROFILE: 'بروفايل المستخدم',
            CHAT: 'الدردشة',
            DELETE: 'مسح',
            ADD_TEAM_MEMBERS: 'اضافة عضو الى الفريق',
            JOIN_DATE: 'تاريخ الانضمام:',
            USER_ID: 'رقم الهوية:',
            ADDRESS: 'العنوان:',
            ABOUT_ME: 'عني:',
            LOGIN_PAGE: 'صفحة الدخول',
            RENOVATION_NUMBER_I_AM_IN: 'عدد التصليحات المشترك بها:',
            REQUIRED: 'حقل اجباري',
            WRONG_EMAIL: ' عنوان بريد خاطئ',
            PASSWORD: 'الرقم السري',
            FORGOT_PASSWORD: 'نسيت الرقم السري',
            PASSWORD_LENGTH: 'مطلوب 9 ارقام على الاقل',
            PASSWORD_MIN_LENGTH: 'مطلوب 8 حروف على الأقل',
            PASSWORD_TIP: ' مطلوب رقم سري باللغة الانجليزية مع حرف واحد كبير وحرف صغير ورقم على الأقل',
            LOGIN: 'دخول',
            COMPLETE_REGISTERATION: 'اكمال عملية التسجيل',
            ILLEGAL_NUMBER: 'الرقم غير قانوني',
            VOLUNTEERING_AREA: 'المنطقة التي اريد ان اتطوع بها -',
            MULTIPLE_AREAS_CAN_BE_SELECTED: 'يمكن اختيار عدة مناطق',
            PREFERED_DAY: 'اذا كنت تفضل يوم معين بالأسبوع : الرجاء ذكرة',
            TIME_IN_DAY: 'בוקר - 9:00 עד 14:00 אחה"צ - 16:00 עד 21:00',
            DO_YOU_WANT_TO_BE_TEAM_LEAD: 'هل انت\ي مهتم بأن تصبح\ي قائد فريق ؟',
            TEAM_LEAD_ROLE: 'לראש הצוות יש שני תפקידים עיקריים: לבקר בבית המיועד לשיפוץ ולהכיןתוכנית, ולהיות אחראי על התיאומים מול הצוות שלו.',
            PREFERED_HATED_FIELD: '*** هل يوجد اي مجال تقني انت\ي جيد\ة به ؟',
            PREFERED_HATED_FIELD_EXAMPLE: 'לדוגמא: בנייה בעץ, קרמיקה, חשמל, מנעולים, תריסים, צבע, עיצוב פנים וכו” כל מה שיכול לעזור...',
            REGISTER_MESSAGE: 'للتطوع في مشروح يديّم',
            REGISTERED_SUCCESSFULLY: 'تم التسجيل بنجاح',
            CHECK_EMAIL_TO_CONTINUE: 'الرجاء فحص الأميل لأكمال عملية التسجيل',
            FULL_NAME: 'الأسم الشخصي وأسم العائلة',
            BACK_TO_HOME_PAGE: 'الرجوع للصفحة الرئيسية',
            BUTTON_LANG_HE: 'العبرية',
            BUTTON_LANG_AR: 'العربية'
        };

        this.$get = function () {
            return this;
        };

    });